name = "LoveIt"
license = "MIT"
licenselink = "https://github.com/codemikko/mikkocodes/blob/master/LICENSE"
description = "The most Safisticated and Elegant, Advanced Hugo Theme there is... for Hugo."
homepage = "https://mikko.codes"
demosite = "https://suspicious-archimedes-ab369d.netlify.app/"
tags = ["blog", "clean", "responsive", "dark", "theme"]
features = [
  "cover-image",
  "favicon",
  "multilingual",
  "pagination",
  "social-menu",
  "syntax-highlighting",
  "SEO Optimized"
]
min_version = "0.62.0"

[author]
name = "Mikko"
homepage = "https://mikko.codes"

[original]
name = "Dillon"
homepage = "https://dillonzq.com/"
repo = "https://github.com/dillonzq/LoveIt"
